### ISSUE TITLE
ToDo tasks 

### ISSUE THREAD

**Issue by samthakur587** [samthakur587/LLM_playground#1]
- [x] Make the Unify API key invisible by default 
- [x] combining model and provider into a single field
- [x] Add chat history to the model
