### ISSUE TITLE
ToDo tasks

### ISSUE THREAD

**Issue by Kacper-W-Kozdon** [samthakur587/LLM_playground#8]
ToDo tasks:
- [x] #9
- [x] #10
- [x] #18
- [x] #15
- [x] create gcp deployment template
- [ ] move from hosting on streamlit to hosting on google cloud
- [ ] make the .streamlit/secrets.toml actually secret
- [ ] add unit test for all function
- [x] #16
- [x] #20
- [x] #22
- [ ] #24
- [ ] #25
- [ ] #29
- [ ] #28
